import type { Flashcard } from "../types";

/**
 * 보강 카드 묶음. 기존 theory/machine/facility 에 빈 곳을 채우는 추가 문항.
 * id 접두사: x-
 *
 * 모든 카드의 topic 은 chapters.ts CHAPTERS 안의 챕터명과 정확히 일치해야 함.
 */
export const extraCards: Flashcard[] = [
  // ===== 전기이론 =====
  {
    id: "x-power-units",
    front: "전력의 단위와 환산 (W, kW, HP)?",
    back: "$1\\ \\text{kW} = 1{,}000\\ \\text{W}$\n$1\\ \\text{HP} \\approx 746\\ \\text{W} \\ (\\text{영국마력})$\n$1\\ \\text{PS} \\approx 735\\ \\text{W} \\ (\\text{미터마력})$",
    subject: "전기이론",
    topic: "직류회로",
    source: "extra",
    hint: "HP·PS 환산 자주 출제",
    example: {
      question: "$5\\ \\text{HP}$ 전동기의 출력은 약 몇 kW?",
      solution: [
        "$1\\ \\text{HP} \\approx 746\\ \\text{W}$",
        "$5 \\times 746 = 3{,}730\\ \\text{W} \\approx 3.73\\ \\text{kW}$",
      ],
      answer: "약 3.73 kW",
    },
  },
  {
    id: "x-electric-energy",
    front: "전력량(W·h)의 정의와 단위 변환?",
    back: "$W = P \\cdot t$ [$\\text{W} \\cdot \\text{h}$]\n$1\\ \\text{kWh} = 3{,}600\\ \\text{kJ}$\n$1\\ \\text{Wh} = 3{,}600\\ \\text{J}$\n전기요금 계산 단위.",
    subject: "전기이론",
    topic: "직류회로",
    source: "extra",
    hint: "1 kWh = 3600 kJ",
    example: {
      question: "$2\\ \\text{kW}$ 전열기를 5시간 사용했을 때 전력량은 몇 kWh?",
      solution: ["$W = 2\\ \\text{kW} \\times 5\\ \\text{h} = 10\\ \\text{kWh}$"],
      answer: "$10\\ \\text{kWh}$",
    },
  },
  {
    id: "x-joule-heat",
    front: "줄(Joule)의 법칙 — 전류의 열작용?",
    back: "$H = I^2 R t$ [J]\n$= 0.24\\, I^2 R t$ [cal] (1 J ≈ 0.24 cal)\n저항에서 발생하는 열량.",
    subject: "전기이론",
    topic: "직류회로",
    source: "extra",
    hint: "I² R t",
    example: {
      question: "$2\\ \\text{A}$가 $10\\ \\Omega$ 저항에 1분간 흐를 때 발생 열량 [J]은?",
      solution: ["$H = I^2 R t = 2^2 \\times 10 \\times 60$", "$= 2{,}400\\ \\text{J}$"],
      answer: "$2{,}400\\ \\text{J}$",
    },
  },
  {
    id: "x-coulomb",
    front: "쿨롱(Coulomb)과 전류·전하 관계?",
    back: "$Q = I \\cdot t$ [C]\n$1\\ \\text{C} = 1\\ \\text{A} \\times 1\\ \\text{s}$\n전자 1개의 전하: $e = 1.602 \\times 10^{-19}\\ \\text{C}$",
    subject: "전기이론",
    topic: "정전기",
    source: "extra",
    hint: "전류 × 시간",
    example: {
      question: "$0.5\\ \\text{A}$가 2분 동안 흐를 때 이동 전하량은?",
      solution: [
        "$Q = I \\cdot t$",
        "$Q = 0.5 \\times 120 = 60\\ \\text{C}$",
      ],
      answer: "$Q = 60\\ \\text{C}$",
    },
  },
  {
    id: "x-capacitor-energy",
    front: "콘덴서에 저장되는 에너지?",
    back: "$W = \\dfrac{1}{2} C V^2 = \\dfrac{1}{2} Q V = \\dfrac{Q^2}{2C}$ [J]\n전압·전하·정전용량 중 둘만 알면 계산 가능.",
    subject: "전기이론",
    topic: "정전기",
    source: "extra",
    hint: "½ CV² 가장 흔함",
    example: {
      question: "$100\\ \\mu\\text{F}$ 콘덴서에 $200\\ \\text{V}$가 걸렸을 때 저장 에너지는?",
      solution: [
        "$W = \\dfrac{1}{2} C V^2$",
        "$= \\dfrac{1}{2} \\times 100 \\times 10^{-6} \\times 200^2$",
        "$= 2\\ \\text{J}$",
      ],
      answer: "$2\\ \\text{J}$",
    },
  },
  {
    id: "x-dielectric",
    front: "유전체 삽입 시 정전용량 변화?",
    back: "$C = \\varepsilon_r \\cdot C_0$\n유전체의 비유전율 $\\varepsilon_r$ 배만큼 정전용량 증가.\n공기 $\\varepsilon_r = 1$, 종이 약 $2$~$4$, 세라믹 수십~수천.",
    subject: "전기이론",
    topic: "정전기",
    source: "extra",
    hint: "비유전율 배수만큼 ↑",
    example: {
      question: "공기 콘덴서 정전용량이 $5\\ \\mu\\text{F}$일 때 비유전율 4인 종이를 채우면?",
      solution: [
        "$C = \\varepsilon_r \\cdot C_0$",
        "$C = 4 \\times 5 = 20\\ \\mu\\text{F}$",
      ],
      answer: "$C = 20\\ \\mu\\text{F}$",
    },
  },
  {
    id: "x-flux-density",
    front: "자속 밀도 B 의 정의와 단위?",
    back: "$B = \\dfrac{\\phi}{A}$ [$\\text{Wb}/\\text{m}^2$ = T(테슬라)]\n$1\\ \\text{T} = 10{,}000\\ \\text{Gauss}$\n자속이 얼마나 빽빽한지 나타냄.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "extra",
    hint: "T = Wb/m²",
    example: {
      question: "면적 $0.01\\ \\text{m}^2$를 통과하는 자속이 $0.05\\ \\text{Wb}$일 때 자속밀도는?",
      solution: [
        "$B = \\dfrac{\\phi}{A}$",
        "$B = \\dfrac{0.05}{0.01} = 5\\ \\text{T}$",
      ],
      answer: "$B = 5\\ \\text{T}$",
    },
  },
  {
    id: "x-permeability",
    front: "투자율 μ 의 의미와 상대 투자율?",
    back: "$\\mu = \\mu_0 \\cdot \\mu_r$\n진공 $\\mu_0 = 4\\pi \\times 10^{-7}$ [H/m]\n강자성체 $\\mu_r \\gg 1$ (철 수천), 비자성체 $\\mu_r \\approx 1$.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "extra",
    hint: "강자성체 = μ_r 큼",
    example: {
      question: "비투자율 1000인 철심의 투자율 $\\mu$는?",
      solution: [
        "$\\mu = \\mu_0 \\mu_r$",
        "$\\mu = 4\\pi \\times 10^{-7} \\times 1000$",
        "$\\mu \\approx 1.26 \\times 10^{-3}\\ \\text{H/m}$",
      ],
      answer: "$\\mu \\approx 1.26 \\times 10^{-3}\\ \\text{H/m}$",
    },
  },
  {
    id: "x-mmf",
    front: "기자력(MMF) 의 정의?",
    back: "$F = N \\cdot I$ [AT, 암페어 턴]\n자속을 만드는 능력. 코일 권수 × 전류.\n자기회로의 '전원'에 해당.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "extra",
    hint: "권수 × 전류 = AT",
    example: {
      question: "권수 300, 전류 0.5 A인 코일의 기자력은?",
      solution: [
        "$F = N \\cdot I$",
        "$F = 300 \\times 0.5 = 150\\ \\text{AT}$",
      ],
      answer: "$F = 150\\ \\text{AT}$",
    },
  },
  {
    id: "x-magnetic-reluctance",
    front: "자기저항(릴럭턴스)?",
    back: "$R_m = \\dfrac{l}{\\mu A}$ [AT/Wb]\n자속이 흐르기 어려운 정도.\n자기 옴의 법칙: $\\phi = \\dfrac{F}{R_m}$",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "extra",
    hint: "자기판 옴의 법칙",
    example: {
      question: "기자력 200 AT, 자기저항 $4 \\times 10^4$ AT/Wb일 때 자속은?",
      solution: [
        "$\\phi = \\dfrac{F}{R_m}$",
        "$\\phi = \\dfrac{200}{4 \\times 10^4} = 5 \\times 10^{-3}\\ \\text{Wb}$",
      ],
      answer: "$\\phi = 5\\ \\text{mWb}$",
    },
  },
  {
    id: "x-self-inductance",
    front: "자체 인덕턴스 L 정의?",
    back: "$L = \\dfrac{N \\phi}{I}$ [H, 헨리]\n자기 자신의 전류 변화에 대한 역기전력 계수.\n$e = -L \\dfrac{di}{dt}$",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "extra",
    hint: "전류 변화 ↔ 역기전력",
    example: {
      question: "권수 200, 전류 2 A일 때 자속 $5 \\times 10^{-3}$ Wb이 발생하는 코일의 자체 인덕턴스는?",
      solution: [
        "$L = \\dfrac{N \\phi}{I}$",
        "$L = \\dfrac{200 \\times 5 \\times 10^{-3}}{2}$",
        "$L = 0.5\\ \\text{H}$",
      ],
      answer: "$L = 0.5\\ \\text{H}$",
    },
  },
  {
    id: "x-inductor-energy",
    front: "인덕터(코일)에 저장되는 에너지?",
    back: "$W = \\dfrac{1}{2} L I^2$ [J]\n자기장 형태로 저장.\n전류가 끊기면 역기전력으로 방출(아크 원인).",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "extra",
    hint: "½ L I²",
    example: {
      question: "$L = 0.2$ H 인덕터에 3 A가 흐를 때 저장 에너지는?",
      solution: [
        "$W = \\dfrac{1}{2} L I^2$",
        "$W = \\dfrac{1}{2} \\times 0.2 \\times 9$",
        "$W = 0.9\\ \\text{J}$",
      ],
      answer: "$W = 0.9\\ \\text{J}$",
    },
  },
  {
    id: "x-impedance-rl",
    front: "RL 직렬 임피던스 크기와 위상?",
    back: "$|Z| = \\sqrt{R^2 + (\\omega L)^2}$\n$\\theta = \\tan^{-1}\\dfrac{\\omega L}{R}$ (전류가 전압보다 뒤짐)\n유도성 회로 = 전류 지상.",
    subject: "전기이론",
    topic: "교류회로",
    source: "extra",
    hint: "L 회로 = 전류 지상",
    example: {
      question: "$R = 3\\ \\Omega$, $\\omega L = 4\\ \\Omega$인 RL 직렬 회로의 임피던스 크기는?",
      solution: [
        "$|Z| = \\sqrt{R^2 + (\\omega L)^2}$",
        "$|Z| = \\sqrt{9 + 16} = 5\\ \\Omega$",
      ],
      answer: "$|Z| = 5\\ \\Omega$",
    },
  },
  {
    id: "x-impedance-rc",
    front: "RC 직렬 임피던스 크기와 위상?",
    back: "$|Z| = \\sqrt{R^2 + \\bigl(\\dfrac{1}{\\omega C}\\bigr)^2}$\n$\\theta = -\\tan^{-1}\\dfrac{1}{\\omega C R}$ (전류가 전압보다 앞섬)\n용량성 회로 = 전류 진상.",
    subject: "전기이론",
    topic: "교류회로",
    source: "extra",
    hint: "C 회로 = 전류 진상",
    example: {
      question: "$R = 6\\ \\Omega$, $\\dfrac{1}{\\omega C} = 8\\ \\Omega$인 RC 직렬 회로의 임피던스 크기는?",
      solution: [
        "$|Z| = \\sqrt{R^2 + X_C^2}$",
        "$|Z| = \\sqrt{36 + 64} = 10\\ \\Omega$",
      ],
      answer: "$|Z| = 10\\ \\Omega$",
    },
  },
  {
    id: "x-power-factor",
    front: "역률(Power Factor)의 의미?",
    back: "$\\text{p.f.} = \\cos\\theta = \\dfrac{P}{S}$\nP: 유효전력, S: 피상전력.\n역률이 낮으면 송전 손실 증가 → 콘덴서로 개선(역률 개선).",
    subject: "전기이론",
    topic: "교류회로",
    source: "extra",
    hint: "P/S = cosθ",
    example: {
      question: "유효전력 80 kW, 피상전력 100 kVA인 부하의 역률은?",
      solution: [
        "$\\cos\\theta = \\dfrac{P}{S}$",
        "$\\cos\\theta = \\dfrac{80}{100} = 0.8$",
      ],
      answer: "역률 0.8",
    },
  },
  {
    id: "x-three-phase-power",
    front: "3상 평형 부하의 유효전력?",
    back: "$P = \\sqrt{3}\\, V_L \\, I_L \\, \\cos\\theta$ [W]\n$V_L$: 선간전압, $I_L$: 선전류.\n무효 $Q = \\sqrt{3} V_L I_L \\sin\\theta$, 피상 $S = \\sqrt{3} V_L I_L$",
    subject: "전기이론",
    topic: "3상 교류",
    source: "extra",
    hint: "√3 V_L I_L cosθ",
    example: {
      question: "선간전압 380 V, 선전류 10 A, 역률 0.9인 3상 평형 부하의 유효전력은?",
      solution: [
        "$P = \\sqrt{3}\\, V_L I_L \\cos\\theta$",
        "$P = 1.732 \\times 380 \\times 10 \\times 0.9$",
        "$P \\approx 5{,}924\\ \\text{W} \\approx 5.92\\ \\text{kW}$",
      ],
      answer: "약 5.92 kW",
    },
  },
  {
    id: "x-y-delta",
    front: "Y(스타) 결선과 Δ(델타) 결선 관계?",
    back: "Y 결선: $V_L = \\sqrt{3}\\, V_P$, $I_L = I_P$\nΔ 결선: $V_L = V_P$, $I_L = \\sqrt{3}\\, I_P$\nL: 선간, P: 상.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "extra",
    hint: "Y는 V에 √3, Δ는 I에 √3",
    example: {
      question: "Y결선에서 상전압이 220 V일 때 선간전압은?",
      solution: [
        "Y: $V_L = \\sqrt{3}\\, V_P$",
        "$V_L = 1.732 \\times 220 \\approx 381\\ \\text{V}$",
      ],
      answer: "약 380 V",
    },
  },
  {
    id: "x-form-factor",
    front: "정현파의 파형률·파고율?",
    back: "정현파 기준:\n실효값 $I_{rms} = \\dfrac{I_m}{\\sqrt{2}} \\approx 0.707 I_m$\n평균값 $I_{avg} = \\dfrac{2 I_m}{\\pi} \\approx 0.637 I_m$\n파형률 $= \\dfrac{rms}{avg} \\approx 1.11$, 파고율 $= \\dfrac{I_m}{rms} \\approx 1.414$",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "extra",
    hint: "1.11 / 1.414",
    example: {
      question: "최댓값 100 V인 정현파의 실효값과 평균값은?",
      solution: [
        "실효값 $= \\dfrac{V_m}{\\sqrt{2}} \\approx 0.707 \\times 100 \\approx 70.7\\ \\text{V}$",
        "평균값 $= \\dfrac{2 V_m}{\\pi} \\approx 0.637 \\times 100 \\approx 63.7\\ \\text{V}$",
      ],
      answer: "실효값 ≈ 70.7 V, 평균값 ≈ 63.7 V",
    },
  },
  {
    id: "x-thd",
    front: "고조파와 왜형률(THD)?",
    back: "비정현파 = 기본파 + 고조파의 합\n왜형률 = $\\dfrac{\\sqrt{\\sum (V_n)^2}}{V_1} \\times 100\\%$ ($n \\ge 2$)\n전원의 순도가 떨어질수록 ↑",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "extra",
    hint: "고조파 합 / 기본파",
    example: {
      question: "기본파 100 V, 3고조파 30 V, 5고조파 40 V만 있을 때 왜형률은?",
      solution: [
        "분자 = $\\sqrt{30^2 + 40^2} = \\sqrt{900 + 1600} = 50$",
        "THD $= \\dfrac{50}{100} \\times 100 = 50\\%$",
      ],
      answer: "50 %",
    },
  },
  {
    id: "x-thevenin",
    front: "테브난(Thevenin) 등가회로?",
    back: "임의의 두 단자에서 본 회로는 다음과 동등:\n전압원 $V_{TH}$(개방전압) + 직렬 저항 $R_{TH}$(전원 모두 죽인 상태에서 두 단자에서 본 저항)",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "extra",
    hint: "V_open + 등가저항",
    example: {
      question: "테브난 등가회로의 두 요소는?",
      solution: [
        "개방 단자 전압 → $V_{TH}$",
        "전원을 모두 제거하고 본 등가저항 → $R_{TH}$",
      ],
      answer: "$V_{TH}$(개방전압) + $R_{TH}$(직렬)",
    },
  },
  {
    id: "x-superposition",
    front: "중첩의 원리?",
    back: "선형회로에서는 각 전원이 단독으로 작용할 때의 결과를 모두 합하면 전체 응답.\n전압원은 단락, 전류원은 개방으로 처리.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "extra",
    hint: "선형 + 합산",
    example: {
      question: "중첩의 원리에서 다른 전원을 어떻게 처리하는가?",
      solution: [
        "전압원: 단락(0 V)",
        "전류원: 개방(0 A)",
        "각 전원 단독 해석 후 합산",
      ],
      answer: "전압원 단락 / 전류원 개방",
    },
  },

  // ===== 전기기기 =====
  {
    id: "x-dc-emf",
    front: "직류기 유기기전력 식?",
    back: "$E = \\dfrac{P \\, Z \\, \\phi \\, N}{60 \\, a}$ [V]\n$P$ 극수, $Z$ 도체수, $\\phi$ 자속, $N$ 회전수[rpm], $a$ 병렬회로수\n중권 $a = P$, 파권 $a = 2$.",
    subject: "전기기기",
    topic: "직류기",
    source: "extra",
    hint: "PZφN/60a",
    example: {
      question: "$P=6$, $Z=300$, $\\phi=0.02$ Wb, $N=1200$ rpm, 중권($a=P$)인 직류기 기전력은?",
      solution: [
        "$a = P = 6$",
        "$E = \\dfrac{6 \\times 300 \\times 0.02 \\times 1200}{60 \\times 6}$",
        "$E = \\dfrac{43200}{360} = 120\\ \\text{V}$",
      ],
      answer: "$E = 120\\ \\text{V}$",
    },
  },
  {
    id: "x-dc-torque",
    front: "직류 전동기 토크?",
    back: "$T = \\dfrac{P \\, Z \\, \\phi \\, I_a}{2\\pi a}$ [N·m]\n토크는 자속 × 전기자전류 에 비례 ($T \\propto \\phi I_a$).",
    subject: "전기기기",
    topic: "직류기",
    source: "extra",
    hint: "T ∝ φ I_a",
    example: {
      question: "자속을 일정하게 두고 전기자전류를 2배로 늘리면 직류 전동기 토크는?",
      solution: [
        "$T \\propto \\phi I_a$",
        "$\\phi$ 일정 → 토크는 $I_a$에 비례",
      ],
      answer: "2배",
    },
  },
  {
    id: "x-transformer-loss",
    front: "변압기 손실의 종류?",
    back: "고정손(무부하손) = 철손 = 히스테리시스 + 와류손\n부하손 = 동손 = $I^2 R$\n변압기 효율 최대: 철손 = 동손 일 때.",
    subject: "전기기기",
    topic: "변압기",
    source: "extra",
    hint: "철손 = 동손에서 최대 효율",
    example: {
      question: "정격 동손 400 W, 철손 100 W인 변압기에서 최대 효율점 부하율은?",
      solution: [
        "최대효율: 철손 = (부하율)² × 정격동손",
        "$100 = k^2 \\times 400 \\Rightarrow k = 0.5$",
      ],
      answer: "부하율 50 %",
    },
  },
  {
    id: "x-transformer-regulation",
    front: "변압기 전압 변동률?",
    back: "$\\varepsilon = \\dfrac{V_{2,\\text{무부하}} - V_{2,\\text{전부하}}}{V_{2,\\text{전부하}}} \\times 100\\%$\n낮을수록 정전압 특성 우수.",
    subject: "전기기기",
    topic: "변압기",
    source: "extra",
    hint: "낮을수록 좋음",
    example: {
      question: "무부하 단자전압 210 V, 전부하 단자전압 200 V인 변압기의 전압변동률은?",
      solution: [
        "$\\varepsilon = \\dfrac{V_0 - V_n}{V_n} \\times 100$",
        "$\\varepsilon = \\dfrac{210 - 200}{200} \\times 100 = 5\\%$",
      ],
      answer: "5 %",
    },
  },
  {
    id: "x-sync-speed",
    front: "유도전동기 동기속도?",
    back: "$N_s = \\dfrac{120 f}{P}$ [rpm]\n$f$ 주파수, $P$ 극수.\n60Hz·4극 → $N_s = 1{,}800$ rpm.",
    subject: "전기기기",
    topic: "유도전동기",
    source: "extra",
    hint: "120f/P",
    example: {
      question: "60 Hz, 6극 유도전동기의 동기속도는?",
      solution: [
        "$N_s = \\dfrac{120 f}{P}$",
        "$N_s = \\dfrac{120 \\times 60}{6} = 1200\\ \\text{rpm}$",
      ],
      answer: "$N_s = 1200\\ \\text{rpm}$",
    },
  },
  {
    id: "x-slip",
    front: "유도전동기 슬립?",
    back: "$s = \\dfrac{N_s - N}{N_s}$\n동기속도 $N_s$와 실제 회전속도 $N$의 차이 비율.\n무부하 $s \\approx 0$, 정지 $s = 1$.",
    subject: "전기기기",
    topic: "유도전동기",
    source: "extra",
    hint: "동기속도 대비 차이",
    example: {
      question: "동기속도 1,800 rpm 인 유도전동기가 1,728 rpm 으로 회전 중일 때 슬립은?",
      solution: [
        "$s = \\dfrac{1800 - 1728}{1800} = \\dfrac{72}{1800}$",
        "$s = 0.04\\ (4\\%)$",
      ],
      answer: "$s = 0.04$ (4 %)",
    },
  },
  {
    id: "x-sync-machine",
    front: "동기기 — 회전자 종류?",
    back: "돌극형(salient pole): 저속·다극 (수차 발전기)\n원통형(cylindrical): 고속·소극수 (터빈 발전기)",
    subject: "전기기기",
    topic: "동기기",
    source: "extra",
    hint: "수차=돌극, 터빈=원통",
    example: {
      question: "고속회전(고속 증기 터빈)에 사용되는 동기발전기 회전자 형식은?",
      solution: [
        "고속 → 원심력 견딜 수 있는 원통형",
      ],
      answer: "원통형(cylindrical)",
    },
  },
  {
    id: "x-rectifier-types",
    front: "정류 회로 종류와 출력 직류 전압?",
    back: "단상 반파: $V_{dc} = 0.45\\, V$\n단상 전파: $V_{dc} = 0.9\\, V$\n3상 반파: $V_{dc} = 1.17\\, V$\n3상 전파: $V_{dc} = 1.35\\, V$\n(V는 입력 실효값)",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "extra",
    hint: "전파일수록 평활도 좋음",
    example: {
      question: "교류 실효값 100 V를 단상 전파 정류했을 때 직류 평균전압은?",
      solution: [
        "$V_{dc} = 0.9 V$",
        "$V_{dc} = 0.9 \\times 100 = 90\\ \\text{V}$",
      ],
      answer: "$V_{dc} = 90\\ \\text{V}$",
    },
  },
  {
    id: "x-thyristor",
    front: "사이리스터(SCR) 동작?",
    back: "P-N-P-N 4층 반도체. 게이트 신호로 ON, 한 번 ON 되면 게이트로 OFF 불가.\n전류가 유지전류 이하로 떨어지면 OFF.",
    subject: "전기기기",
    topic: "제어기기",
    source: "extra",
    hint: "게이트로 켜고 전류로 꺼짐",
    example: {
      question: "한 번 ON된 SCR을 OFF시키는 일반적 방법은?",
      solution: [
        "게이트로는 OFF 불가",
        "전류를 유지전류 이하로 낮춤",
      ],
      answer: "전류를 유지전류 이하로 강하 (또는 역전압 인가)",
    },
  },
  {
    id: "x-relay-types",
    front: "보호 계전기 — 자주 출제되는 종류?",
    back: "과전류 계전기(OCR): 정정값 이상 전류 흐를 때\n과전압 계전기(OVR) / 부족전압(UVR)\n차동 계전기(DCR): 변압기 양단 전류차 검출\n비율차동·거리·방향성 등",
    subject: "전기기기",
    topic: "제어기기",
    source: "extra",
    hint: "OCR / OVR / DCR",
    example: {
      question: "정정값 이상의 과전류가 흐를 때 동작하는 보호 계전기는?",
      solution: [
        "과전류 검출 전용",
        "→ OCR (Over Current Relay)",
      ],
      answer: "OCR",
    },
  },
  {
    id: "x-insulation-class",
    front: "전기기기 절연 종별과 허용 온도?",
    back: "Y: 90 ℃ · A: 105 ℃ · E: 120 ℃\nB: 130 ℃ · F: 155 ℃\nH: 180 ℃ · C: 180 ℃ 초과\n허용 온도 = 권선의 최고 사용 온도.",
    subject: "전기기기",
    topic: "시험·정격",
    source: "extra",
    hint: "Y<A<E<B<F<H<C",
    example: {
      question: "허용 최고온도가 130 ℃인 절연물의 종별은?",
      solution: [
        "Y90 / A105 / E120 / B130",
        "→ B종",
      ],
      answer: "B종",
    },
  },

  // ===== 전기설비 =====
  {
    id: "x-conductor-ampacity",
    front: "전선의 허용전류 결정 요소?",
    back: "전선 굵기(단면적), 절연체 종류·허용 온도,\n주위 온도, 설치 방법(공중·관 내·매설),\n동시에 사용하는 회선 수.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "extra",
    hint: "굵기·절연·환경",
    example: {
      question: "같은 굵기·절연의 전선을 한 관에 더 많이 묶어 포설하면 허용전류는?",
      solution: [
        "방열 저하 → 감소계수 적용",
        "허용전류 감소",
      ],
      answer: "감소",
    },
  },
  {
    id: "x-voltage-drop",
    front: "전압강하 공식 (단상 2선)?",
    back: "$e = \\dfrac{35.6\\, L\\, I}{1000\\, A}$ [V]\n$L$ 거리[m], $I$ 전류[A], $A$ 단면적[mm²].\n3상 3선식: $e = \\dfrac{30.8\\, L\\, I}{1000\\, A}$",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "extra",
    hint: "단상 35.6 / 3상 30.8",
    example: {
      question: "단상 2선식, 100 m, 10 A, 단면적 4 mm²의 전압강하는?",
      solution: [
        "$e = \\dfrac{35.6 \\times L \\times I}{1000 \\times A}$",
        "$e = \\dfrac{35.6 \\times 100 \\times 10}{1000 \\times 4}$",
        "$e = \\dfrac{35600}{4000} = 8.9\\ \\text{V}$",
      ],
      answer: "약 8.9 V",
    },
  },
  {
    id: "x-wire-color",
    front: "저압 옥내 배선 — 전선 색별 표시?",
    back: "L1(R) 갈색, L2(S) 검정, L3(T) 회색\n중성선 N: 파란색\n보호도체 PE: 녹색-노란색 (스트라이프)",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "extra",
    hint: "PE = 녹색-노랑",
    example: {
      question: "분전반 결선에서 녹색-노랑 줄무늬 전선은 어느 도체인가?",
      solution: [
        "녹/황 줄무늬 = 보호도체 전용 색",
      ],
      answer: "보호도체(PE)",
    },
  },
  {
    id: "x-pliers",
    front: "전기 공구 — 펜치·롱노즈·니퍼 용도?",
    back: "펜치(plier): 전선 잡기·구부리기·끊기\n롱노즈(long-nose): 좁은 곳 작업·작은 부품 잡기\n니퍼(nipper): 전선 절단 전용\n압착펜치: 단자·슬리브 압착",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "extra",
    hint: "펜치=다용도, 니퍼=절단",
    example: {
      question: "단자에 압착 슬리브를 끼우고 단단히 압착할 때 사용하는 공구는?",
      solution: [
        "단자·슬리브 압착 전용",
        "→ 압착펜치",
      ],
      answer: "압착펜치",
    },
  },
  {
    id: "x-conduit-types",
    front: "전선관 종류?",
    back: "금속관: 후강·박강·합성수지 강관 (강도↑)\n합성수지관: PVC·CD관 (절연·내식)\n가요전선관: 진동·이동 부위에 사용\n금속몰드·합성수지몰드: 노출 배선용",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "extra",
    hint: "강도→금속, 절연→PVC",
    example: {
      question: "전동기처럼 진동·이동이 있는 부위의 배선에 적합한 전선관은?",
      solution: [
        "구부림·진동에 강한 관",
        "→ 가요전선관",
      ],
      answer: "가요전선관",
    },
  },
  {
    id: "x-conduit-fill",
    front: "전선관 굵기 산정 — 점유율?",
    back: "전선 한 종류: 단면적 합 ÷ 관 내 단면적 ≤ 48%\n서로 다른 굵기 혼용: ≤ 32% (방열·인입 여유)",
    subject: "전기설비",
    topic: "배선공사",
    source: "extra",
    hint: "동일 48 / 혼합 32",
    example: {
      question: "관 내 단면적 200 mm²의 전선관에 다른 굵기 전선을 혼합 수용할 때 최대 점유 단면적은?",
      solution: [
        "혼합 점유율 32 %",
        "$200 \\times 0.32 = 64\\ \\text{mm}^2$",
      ],
      answer: "약 64 mm² 이하",
    },
  },
  {
    id: "x-conduit-bend",
    front: "금속 전선관 굽힘 — 굴곡 반경?",
    back: "곡률 반경 ≥ 관 안지름의 6배 (절연전선 통과 시 8배)\n직각 굴곡은 4개소까지, 누계 360° 이하.\n무리한 굽힘은 절연 손상·인입 불가 원인.",
    subject: "전기설비",
    topic: "배선공사",
    source: "extra",
    hint: "안지름의 6배 이상",
    example: {
      question: "안지름 28 mm 후강 전선관의 굽힘 곡률 반경은 최소 얼마 이상?",
      solution: [
        "$R \\geq 6 \\times 28$",
        "$R \\geq 168\\ \\text{mm}$",
      ],
      answer: "약 168 mm 이상",
    },
  },
  {
    id: "x-outlet-height",
    front: "콘센트·점멸기 설치 높이 (표준)?",
    back: "콘센트: 바닥에서 0.3 m 이상\n점멸기(스위치): 1.2 m 정도\n전화·통신 단자: 0.3 m 이상\n* 설계·용도에 따라 조정 가능.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "extra",
    hint: "콘센트 0.3 / 스위치 1.2",
    example: {
      question: "일반 옥내 점멸 스위치의 표준 설치 높이는?",
      solution: [
        "주거·일반 사용 편의 기준",
        "→ 약 1.2 m",
      ],
      answer: "약 1.2 m",
    },
  },
  {
    id: "x-grounding-types",
    front: "접지의 종류 (KEC 통합 후)?",
    back: "계통접지: 전력계통 보호 (TN·TT·IT 방식)\n보호접지: 인체 감전 방지\n피뢰접지: 낙뢰 보호\n* 과거 1·2·3종·특별3종 구분은 폐지(2021).",
    subject: "전기설비",
    topic: "접지",
    source: "extra",
    hint: "KEC: 계통/보호/피뢰",
    example: {
      question: "KEC에서 인체 감전 방지 목적으로 기기 외함을 접지하는 것은 어떤 접지로 분류되는가?",
      solution: [
        "인체 감전 보호 목적",
        "→ 보호접지",
      ],
      answer: "보호접지",
    },
  },
  {
    id: "x-ground-resistance",
    front: "접지 저항 — 권장값과 측정법?",
    back: "일반 보호접지: 10 Ω 이하 권장 (설비별 다름)\n측정: 콜라우슈 브리지·접지저항계 (전위강하법)",
    subject: "전기설비",
    topic: "접지",
    source: "extra",
    hint: "10 Ω 이하가 표준",
    example: {
      question: "일반 보호접지의 권장 접지저항 값과 측정에 쓰는 계기는?",
      solution: [
        "권장: 10 Ω 이하",
        "측정: 접지저항계(전위강하 3극법)",
      ],
      answer: "10 Ω 이하 / 접지저항계",
    },
  },
  {
    id: "x-lightning-rod",
    front: "피뢰침의 보호 범위 — 회전구체법?",
    back: "반지름 R 의 가상 구체를 굴려 닿지 않는 영역이 보호 범위.\nR = 20·30·45·60 m (보호레벨 I~IV)\nI 가 가장 엄격(R 작음 → 보호 범위 좁음).",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "extra",
    hint: "구체가 닿지 않는 곳",
    example: {
      question: "회전구체법에서 보호레벨 II의 구체 반지름은?",
      solution: [
        "LPL I=20, II=30, III=45, IV=60 m",
        "→ II는 30 m",
      ],
      answer: "30 m",
    },
  },
  {
    id: "x-spd",
    front: "서지보호장치(SPD)의 역할?",
    back: "낙뢰·개폐 서지로부터 기기 보호.\n과도 과전압을 접지로 우회시켜 잔류전압을 안전 수준으로 낮춤.\nType 1(인입부) / Type 2(분전반) / Type 3(말단) 분류.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "extra",
    hint: "서지 → 대지로 우회",
    example: {
      question: "수전 인입부에 직접 뇌격 서지로부터 보호하기 위해 설치하는 SPD 등급은?",
      solution: [
        "직격뢰 흐름 → 인입부 1차",
        "→ Type 1 SPD",
      ],
      answer: "Type 1",
    },
  },
  {
    id: "x-mccb",
    front: "배선용 차단기(MCCB) 와 누전 차단기(ELCB·RCD) 차이?",
    back: "MCCB: 과전류·단락 차단 (열·전자식 트립)\nELCB / RCD: 누설전류 검출 → 차단 (감전·화재 방지)\n주거 분전반에는 보통 ELCB(RCD) 사용.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "extra",
    hint: "MCCB=과전류, ELCB=누전",
    example: {
      question: "주택 분전반에서 욕실 누전에 의한 감전을 방지하기 위해 사용하는 차단기는?",
      solution: [
        "누설전류 검출 → 차단",
        "→ ELCB(RCD)",
      ],
      answer: "누전차단기(ELCB/RCD)",
    },
  },
  {
    id: "x-fuse-types",
    front: "퓨즈 종류 — 용도별 분류?",
    back: "전력 퓨즈(PF): 고압 변전소·수전반\n실링·관형 퓨즈: 옥내 분기회로\n시한특성: gG(전부하·과부하 모두), gM(전동기 보호) 등",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "extra",
    hint: "gG / gM 특성",
    example: {
      question: "전동기 회로 보호용으로 사용되는 퓨즈의 시한특성 종류는?",
      solution: [
        "전동기는 기동 시 돌입전류 큼",
        "→ gM (전동기 보호 특성)",
      ],
      answer: "gM",
    },
  },
  {
    id: "x-substation-singletrans",
    front: "단권 변압기의 장점?",
    back: "1·2차 코일을 한 코일로 공유 → 동량·철량 적음, 효율↑, 전압변동률↓\n단점: 1·2차 절연 분리 불가 → 사고 시 영향 전파.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "extra",
    hint: "공유로 효율↑ 절연↓",
    example: {
      question: "단권 변압기와 일반 2권선 변압기를 비교했을 때 단권의 장점은?",
      solution: [
        "권선 공유 → 동량·철량 감소",
        "→ 효율↑, 전압변동률↓",
      ],
      answer: "효율 향상·소형·전압변동률 감소",
    },
  },
  {
    id: "x-distribution",
    front: "배전 방식 — 단상 2선·3선식 차이?",
    back: "단상 2선(110/220 V): 가장 단순, 가정용\n단상 3선(110/220 V): 중성선 추가로 2가지 전압 동시 공급, 변압기 효율↑\n불평형 시 중성선에 큰 전류 흐를 수 있음.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "extra",
    hint: "3선식 = 2가지 전압",
    example: {
      question: "한 변압기에서 110 V와 220 V를 동시에 공급할 수 있는 배전 방식은?",
      solution: [
        "중성선 추가로 2가지 전압",
        "→ 단상 3선식",
      ],
      answer: "단상 3선식",
    },
  },
];
